events {}

http {
    upstream backend_servers {
        server ats_backend_1:80 max_fails=2 fail_timeout=10s;
        server ats_backend_2:80 max_fails=2 fail_timeout=10s;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://backend_servers;
            proxy_next_upstream error timeout http_500 http_502 http_503 http_504;
            proxy_connect_timeout 2s;
            proxy_read_timeout 2s;
        }
    }
}
